[project]
name = 'Decentralized-Carbon-Offset-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.offset-verification]
path = 'contracts/offset-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-registration]
path = 'contracts/project-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.trading]
path = 'contracts/trading.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
